name: Update Stable Tag

on:
  push:
    branches:
      - 9.5

permissions:
    contents: read

jobs:
  update-stable-tag:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -f stable
          git push -f origin stable
